# Lectures NGS

Pour vous familiariser avec le contrôle qualité et le prétraitement des données brutes NGS, nous nous exercerons sur de petits sets de données. Les outils utilisés sont disponibles dans Galaxy, une plateforme pour l'analyse de données omiques. 

Avant de continuer : connectez-vous sur le site <https://usegalaxy.fr>. Pour cela, cliquez sur Se connecter ou créer un nouveau compte_ (en haut de la page).

puis pour disposer de ressources suffisantes, allez sur l'url :

<https://usegalaxy.fr/join-training/TD1_Bioinformatique/>

Vous pouvez ensuite retourner sur Galaxy.


## Illumina SE

Optionnel: Vous pouvez renommer votre historique (panneau de droite).

Le 1er set de données concerne une étude métagénomique portant sur le microbiome de la cavité orale d'un serpent. Après extraction et fragmentation de l'ADN de l'échantillon, une partie de gène de l'ARNr 16S a été amplifié puis séquencé (Illumina Single End) afin d'identifier les bactéries présentes. Seule une partie des données sera analysée pour des raisons de temps.

### Raw data: FASTQ file

1. Importez le fichier FASTQ depuis le serveur zenodo : 

Copiez l'adresse du lien 

<https://zenodo.org/record/3977236/files/female_oral2.fastq-4143.gz>

Dans Galaxy, utilisez le bouton *Upload Data* (en haut à gauche) puis *Paste/Fetch dat*a, copiez le lien et lancez (*start*).

2. Regardez le fichier (*eye icon*).

> ❓ Quelles sont les caractéristiques du format FASTQ ?

> ❓ Sachant que les scores sont encodés selon le système SANGER/Illumina 1.8+ (<https://support.illumina.com/help/BaseSpace_Sequence_Hub_OLH_009008_2/Source/Informatics/BS/QualityScoreEncoding_swBS.htm>), quelle est la valeur du score de la plupart des bases au début du 1er read ? Est-ce satisfaisant?
    
### Contrôle qualité avec FastQE et FastQC

Ouvrir le FASTQ Quality Control toolbox (panneau de gauche).

#### FastQE

Explorer la qualité de vos séquences avec FASTQE. “Mean scores” correspond à la moyenne des scores calculées sur toutes les lectures à chaque position. Les scores sont représentés par des emojis (classés de 0 à 41) : 

🚫❌👺💔🙅👾👿💀👻🙈🙉🙊🐵😿😾🙀💣🔥😡💩⚠️
😀😅😏😊😙😗😚😃😘😆😄😋😄😝😛😜😉😁😄😎😍

> ❓ Quelle est la tendance générale pour ce dataset?

#### FastQC

Evaluez plus en détail la qualité des lectures avec FastQC (<https://www.bioinformatics.babraham.ac.uk/projects/fastqc/>. Voir FastQC website pour l'aide et des exemples d'analyse.

> ❓ *Per Base Sequence Quality*:  Quelle est la longueur des lectures ? Comment évolue la qualité le long des lectures ?

> ❓ *Per sequence quality scores*: Que vous apprend ce graphe ?

> ❓ *Per base sequence content*: Dans le cas d'un séquençage de génome (sans amplification), à quoi devrait ressembler ce graphe ? Le résultat obtenu est-il normal dans notre cas ?

> ❓ *Adapter content*: Quel adaptateur est détecté ?

### Read procesing using Trimmomatic

Utilisez Trimmomatic (section FASTQ Quality control) pour améliorer la qualité des lectures :

- *Perform initial IllUMINACLIP step? Yes, select Nextera*

- *Sliding window trimming (proposed by default)*
  
- Ajouter une nouvelle opération Trimmomatic : *Drop reads below a specific length (MINLEN): 20*

> ❓ Quel pourcentage de lectures a été éliminé (voir fichier log) ?

> ❓ Refaites une analyse FastQC sur les lectures après traitement et comparez les résultats aux données brutes. Le résultat est-il acceptable ?

## PacBio Hifi

Ce set de données contient 50 000 lectures PacBio HiFi provenant du séquençage d'un génome humain (PacBio - GIAB sample HG002).

Importez le fichier dans Galaxy :

<https://zenodo.org/api/files/ff9aa6e3-3d69-451f-9798-7ea69b475989/m64011_190830_220126.Q20.subsample.fastq.gz>

Effectuez le contrôle qualité avec Nanoplot (disponible dans Nanopore). Cet outil n'est utilisable que pour les lectures longues (PacBio ou Nanopore) :

- *Options for customizing the plot created:*

  - *Specify the bivariate format of the plots: dot*
  
  - *Show the N50 mark in the read length histogram: Yes*


Analyse: 


> ❓ On observe des variations importantes de taille de lecture dans les données PacBio, contrairement aux données Illumina. Pourquoi ? 

> ❓ Quelle est la longueur moyenne des lectures ?

> ❓ Comment est calculé le N5O dans ce cas ?

Défintion du N50: Dans le cadre de l'assemblage d'un génome: 50% de l’assemblage est couvert par des contigs de longueur N50 ou supérieure. Les contigs sont classés par ordre de longueur décroissante et leur taille additionnée. N50 est la longueur du plus petit contig de la liste nécessaire pour couvrir au moins 50% du génome. Ici nous sommes dans le cadre d'un séquençage et non pas dans le cadre de l'assemblage d'un génome, les contigs sont donc des "reads" (ou "lectures" en français).

> ❓ Quel peut être l'utilité du graphique Yield by length ?

> ❓ Quelle est la qualité moyenne des lectures ?

> ❓ On n'observe aucune lecture avec Q<20. Pourquoi ? Y a-t-il un lien entre taille des lectures et qualité ?


## Nanopore

Le dernier set correspond à des lectures nanopores obtenues à partir d'un génome de plante. Nous allons utiliser PycoQC pour le contrôle qualité. Celui ne fonctionne qu'avec des lectures Nanopores ; il nécessite des informations spécifiques fournies par les basecallers nanopore tels que Guppy.

1. Importez les fichiers dans Galaxy :

<https://zenodo.org/api/files/ff9aa6e3-3d69-451f-9798-7ea69b475989/nanopore_basecalled-guppy.fastq.gz>

<https://zenodo.org/api/files/ff9aa6e3-3d69-451f-9798-7ea69b475989/sequencing_summary.txt>

2. Effectuez le contrôle qualité avec PycoQC

> ❓ Combien de reads sont disponibles ? Combien de bases cela représente ?

> ❓ Comment expliquez-vous l'écart entre taille médiane des lectures et N50 ? (Voir définition du N50 dans la partie PacBio HiFi du TD)

> ❓ Que pouvez-vous dire de la distribution des longueurs ?

> ❓ Dans quel intervalle se situent la plupart des scores de qualité ?