# Exploration des banques de séquences

Dans ce TD, nous explorerons les principales bases de données génomiques publiques : NCBI (Nucléotides, Taxonomie...), UniProt, InterProScan...

## Interrogation des banques par Entrez

Aller sur <http://www.ncbi.nlm.nih.gov/>.

### Utilisation du n° d’accès

Sélectionnez *Nucleotide* sur le site du NCBI et recherchez la séquence NC_045512. De quoi s’agit-il ? Quelle est la longueur du génome ?

> ❓ Consultez le champ *Comment*. De quelle banque provient cette séquence ? Est-elle fiable ? Quelle technologie de séquençage a été utilisée ? Que pouvez-vous dire de cette entrée par rapport à l’entrée initiale GenBank (1ère séquence du génome du SARS-Cov-2) ?

> ❓ Recherchez la région codante correspondant à la protéine N (nucleocapsid phosphoprotein).

> ❓ Que pensez-vous de la composition de cette protéine ? Quel problème peut poser une telle séquence dans une recherche de similarité ?

> ❓ Affichez la séquence du génome au format fasta. Quelles sont les caractéristiques de ce format par rapport au format RefSeq ?

### Recherche par l’annotation (*Filters/Advanced*)

Recherchez dans Nucleotide les séquences comportant le gène BRCA1 pour Homo sapiens envous aidant des filtres ou de la recherche avancée.

> ❓ Pourquoi y a-t-il plusieurs séquences dans RefSeq ? dans Genbank ?

> ❓ Regardez la séquence KT152889. Positionnez rapidement les éléments annotés du gène sur un diagramme. Quelle est la position de la variation sur la séquence ? A quoi correspond-elle (type, codon) ?

> ❓ Parmi les features, la source de la séquence fournit une référence croisée vers la banque Taxonomy du NCBI. Suivez ce lien.

### Banque Taxonomy

> ❓ Quelles sous-espèces humaines sont répertoriées dans la banque Taxonomy ?

> ❓ Quelles autres organismes sont répertoriés au sein des Hominina 
e ?

> ❓ Quels sont les ordres les plus proches de l’ordre des primates ? Lequel d’entre eux a le plus de protéines disponibles ?

> ❓ Combien de génomes sont disponibles dans la banque Genome pour les Animaux, les champignons (Fungi), les plantes (Viridiplantae) et les eucaryotes ? Commentez.

## Recherche de séquences protéiques dans UniProtKb 

Sélectionner la banque UniprotKB (<www.uniprot.org>).

### Utilisation des champs (Advanced search)

> ❓ Combien de séquences protéiques humaines sont répertoriées dans UniprotKB ? dans SwissProt ?

> ❓ Recherchez la protéine associée au gène BRCA1. Comparez les entrées obtenues. Quelle est la meilleure solution ?

### Exemple d’entrée SwissProt

Rechercher la protéine MUC1_HUMAN

> ❓ L’existence de cette protéine est-elle établie (voir Protein existence en haut de page)?

> ❓ Comparez le format proposé par défaut, le format texte et le format fasta (accessibles dans Download).

> ❓ Combien d’isoformes décrites existe-t-il pour cette protéine (voir Sequences) ? Alignez les isoformes (Align) et voyez en quoi elles diffèrent.


### Function – GO annotations

> ❓ La Go ontology permet de décrire les protéines selon 3 aspects. Lesquels ?

> ❓ Suivez le lien de l'entrée GO:0004438.  Qu'est-ce que c'est (nom, description) ? A quel type de GO appartient-il ? Quelle est sa fréquence d'utilisation pour décrire les protéines ?

> ❓ Existe-t-il des synonymes pour ce terme GO ?

### Structure

> ❓ Que pouvez-vous dire des structures obtenues expérimentalement pour la protéine ?

> ❓ Que pouvez-vous dire de la fiabilité de la prédiction AlphaFold pour cette protéine ?

### Onglet *External links* (haut de page)

#### Sequence databases

> ❓ Pourquoi y a-t-il beaucoup plus de liens vers EMBL/GenBank/DDBJ que vers RefSeq ?

#### Families and domains in INTERPRO database

> ❓ Affichez la représentation graphique (View protein in InterPro). Combien y a-t-il de domaines protéiques distincts dans cette protéine ?

Domaine: *IPR000082 SEA domain* 

> ❓ De quelles banques proviennent les 3 signatures associées à ce domaine  InterPro?
  
> ❓ Suivez le lien vers la signature PFAM associée. Affichez la signature.

Dans un nouvel onglet, recherchez la protéine BRCA1_HUMAN dans InterProScan. 

> ❓ Combien y a-t-il de domaines protéiques distincts dans cette protéine ?

> ❓ Suivez le lien  vers la signature PFAM associée au *Zinc finger, C3HC4 type (RING finger)*.  Affichez la signature et comparer là à celle du SEA domain de MUC1. 

> ❓ Regarder la signature ProSite associée  au site conservé *Zinc finger RING-type signature*. Quel est le problème principal du motif ?
